// @generated by protoc-gen-es v2.2.0 with parameter "target=ts,import_extension=js"
// @generated from file monitoring/v1/metrics.proto (package monitoring.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file monitoring/v1/metrics.proto.
 */
export const file_monitoring_v1_metrics: GenFile = /*@__PURE__*/
  fileDesc("Chttb25pdG9yaW5nL3YxL21ldHJpY3MucHJvdG8SDW1vbml0b3JpbmcudjEi3wEKCk1ldHJpY0RhdGESCgoCaWQYASABKAkSEwoLbWV0cmljX3R5cGUYAiABKAkSDQoFdmFsdWUYAyABKAESLQoJdGltZXN0YW1wGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI1CgZsYWJlbHMYBSADKAsyJS5tb25pdG9yaW5nLnYxLk1ldHJpY0RhdGEuTGFiZWxzRW50cnkSDAoEdW5pdBgGIAEoCRotCgtMYWJlbHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIrgBCg1NZXRyaWNTdW1tYXJ5EhMKC21ldHJpY190eXBlGAEgASgJEgsKA21pbhgCIAEoARILCgNtYXgYAyABKAESCwoDYXZnGAQgASgBEg0KBWNvdW50GAUgASgDEi4KCnN0YXJ0X3RpbWUYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiwKCGVuZF90aW1lGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCrqAQoKTWV0cmljVHlwZRIbChdNRVRSSUNfVFlQRV9VTlNQRUNJRklFRBAAEhkKFU1FVFJJQ19UWVBFX0NQVV9VU0FHRRABEhwKGE1FVFJJQ19UWVBFX01FTU9SWV9VU0FHRRACEhcKE01FVFJJQ19UWVBFX0RJU0tfSU8QAxIaChZNRVRSSUNfVFlQRV9ORVRXT1JLX0lPEAQSHAoYTUVUUklDX1RZUEVfUkVRVUVTVF9SQVRFEAUSGgoWTUVUUklDX1RZUEVfRVJST1JfUkFURRAGEhcKE01FVFJJQ19UWVBFX0xBVEVOQ1kQB0J2ChFjb20ubW9uaXRvcmluZy52MUIMTWV0cmljc1Byb3RvUAGiAgNNWFiqAg1Nb25pdG9yaW5nLlYxygINTW9uaXRvcmluZ1xWMeICGU1vbml0b3JpbmdcVjFcR1BCTWV0YWRhdGHqAg5Nb25pdG9yaW5nOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * メトリクスデータ
 *
 * @generated from message monitoring.v1.MetricData
 */
export type MetricData = Message<"monitoring.v1.MetricData"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string metric_type = 2;
   */
  metricType: string;

  /**
   * @generated from field: double value = 3;
   */
  value: number;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: map<string, string> labels = 5;
   */
  labels: { [key: string]: string };

  /**
   * @generated from field: string unit = 6;
   */
  unit: string;
};

/**
 * Describes the message monitoring.v1.MetricData.
 * Use `create(MetricDataSchema)` to create a new message.
 */
export const MetricDataSchema: GenMessage<MetricData> = /*@__PURE__*/
  messageDesc(file_monitoring_v1_metrics, 0);

/**
 * メトリクスサマリー
 *
 * @generated from message monitoring.v1.MetricSummary
 */
export type MetricSummary = Message<"monitoring.v1.MetricSummary"> & {
  /**
   * @generated from field: string metric_type = 1;
   */
  metricType: string;

  /**
   * @generated from field: double min = 2;
   */
  min: number;

  /**
   * @generated from field: double max = 3;
   */
  max: number;

  /**
   * @generated from field: double avg = 4;
   */
  avg: number;

  /**
   * @generated from field: int64 count = 5;
   */
  count: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 6;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 7;
   */
  endTime?: Timestamp;
};

/**
 * Describes the message monitoring.v1.MetricSummary.
 * Use `create(MetricSummarySchema)` to create a new message.
 */
export const MetricSummarySchema: GenMessage<MetricSummary> = /*@__PURE__*/
  messageDesc(file_monitoring_v1_metrics, 1);

/**
 * メトリクスタイプ
 *
 * @generated from enum monitoring.v1.MetricType
 */
export enum MetricType {
  /**
   * @generated from enum value: METRIC_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: METRIC_TYPE_CPU_USAGE = 1;
   */
  CPU_USAGE = 1,

  /**
   * @generated from enum value: METRIC_TYPE_MEMORY_USAGE = 2;
   */
  MEMORY_USAGE = 2,

  /**
   * @generated from enum value: METRIC_TYPE_DISK_IO = 3;
   */
  DISK_IO = 3,

  /**
   * @generated from enum value: METRIC_TYPE_NETWORK_IO = 4;
   */
  NETWORK_IO = 4,

  /**
   * @generated from enum value: METRIC_TYPE_REQUEST_RATE = 5;
   */
  REQUEST_RATE = 5,

  /**
   * @generated from enum value: METRIC_TYPE_ERROR_RATE = 6;
   */
  ERROR_RATE = 6,

  /**
   * @generated from enum value: METRIC_TYPE_LATENCY = 7;
   */
  LATENCY = 7,
}

/**
 * Describes the enum monitoring.v1.MetricType.
 */
export const MetricTypeSchema: GenEnum<MetricType> = /*@__PURE__*/
  enumDesc(file_monitoring_v1_metrics, 0);

